# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:56:45+00:00



import argparse
import json
import os
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity

from models import QuestionsPostRequest

app = MCPProxy(
    contact={'x-twitter': 'Reloadly'},
    description='Polls is a simple API allowing consumers to view polls and vote in them.',
    title='topupsapi',
    version='1.0.0',
    servers=[{'url': 'https://polls.apiblueprint.org'}],
)


@app.get('/questions', tags=['question_management'])
def list__all__questions():
    """
    List All Questions
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/questions',
    description=""" You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices. """,
    tags=['question_management'],
)
def create_a__new__question(body: QuestionsPostRequest = None):
    """
    Create a New Question
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
