# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:56:45+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel, RootModel


class QuestionsCollection(RootModel[Any]):
    root: Any


class QuestionsPostRequest(BaseModel):
    choices: Optional[List[str]] = None
    question: Optional[str] = None
